export class Categores {

    categores = [
        {
            id: '1',
            title: 'МЕХАНИЗМЫ И ТРАНСПОРТ',
            desc: '(авто, гусеничный, ж/д)',
        },
        {
            id: '2',
            title: 'СТРОИТЕЛЬСТВО',
            desc: '',
        },
        {
            id: '3',
            title: 'СВАРОЧНЫЕ ПРОИЗВОДСТВА',
            desc: '',
        },
        {
            id: '4',
            title: 'ЭЛЕКТРОХОЗЯЙСТВО',
            desc: '(эксплуатация, ремонт)',
        },
        {
            id: '5',
            title: 'СЛУЖБА БЫТА',
            desc: '',
        },
        {
            id: '6',
            title: 'НЕФТЕГАЗОВЫЙ КОМПЛЕКС',
            desc: '(разведка, бурение, добыча, эксплуатация)',
        },
        {
            id: '7',
            title: 'МЕД. ПЕРСОНАЛ',
            desc: '',
        }
    ];





    categores_step2 = [
            {
                id: '1',
                idcat: '1',
                title: 'Руководители, ИТР, служащие',
                desc: '',
            },
            {
                id: '2',
                idcat: '1',
                title: 'Слесаря',
                desc: '',
            },
            {
                id: '3',
                idcat: '1',
                title: 'Водители',
                desc: '',
            },
            {
                id: '4',
                idcat: '1',
                title: 'Машинисты колёсной спец. техники',
                desc: '',
            },
            {
                id: '5',
                idcat: '1',
                title: 'Трактористы - машинисты',
                desc: '',
            },
            {
                id: '6',
                idcat: '1',
                title: 'Машинисты гусеничной спецтехники',
                desc: '',
            },
            {
                id: '7',
                idcat: '1',
                title: 'Машинисты ж/д транспорта',
                desc: '',
            },
            {
                id: '8',
                idcat: '1',
                title: 'Машинисты установок',
                desc: '(ДЭС, насосных и тп.)',
            },
            {
                id: '9',
                idcat: '2',
                title: 'Общестроительные работы',
                desc: '',
            },
            {
                id: '10',
                idcat: '2',
                title: 'Технология',
                desc: '',
            },
            {
                id: '11',
                idcat: '2',
                title: 'Электромонтаж',
                desc: '',
            },
            {
                id: '12',
                idcat: '3',
                title: 'Руководители, ИТР, служащие',
                desc: '',
            },
            {
                id: '13',
                idcat: '3',
                title: 'Рабочие профессии',
                desc: '',
            },
        {
            id: '14',
            idcat: '4',
            title: 'проверка',
            desc: '',
        },
        {
            id: '15',
            idcat: '5',
            title: 'проверка',
            desc: '',
        },
        {
            id: '16',
            idcat: '6',
            title: 'проверка',
            desc: '',
        },
        {
            id: '17',
            idcat: '7',
            title: 'проверка',
            desc: '',
        }
    ];



    categores_step3 = [
        {
            id: '1',
            idcat2: '1',
            title: 'Начальник транспортного цеха',
            desc: '',
            tmodel: false,
        },
        {
            id: '2',
            idcat2: '1',
            title: 'Главный механик',
            desc: '',
            tmodel: false,
        },
        {
            id: '3',
            idcat2: '1',
            title: 'Механик',
            desc: '',
            tmodel: false,
        },
        {
            id: '4',
            idcat2: '1',
            title: 'Диспетчер',
            desc: '',
            tmodel: false,
        },
        {
            id: '5',
            idcat2: '2',
            title: 'Автоэлектрик',
            desc: '',
            tmodel: false,
        },
        {
            id: '6',
            idcat2: '2',
            title: 'Слесарь-моторист',
            desc: '',
            tmodel: false,
        },
        {
            id: '7',
            idcat2: '2',
            title: 'Слесарь по топливной аппаратуре',
            desc: '',
            tmodel: false,
        },
        {
            id: '8',
            idcat2: '2',
            title: 'Слесарь по ремонту автомобилей',
            desc: '',
            tmodel: false,
        },
        {
            id: '9',
            idcat2: '2',
            title: 'Слесарь по ремонту и обслуживанию дорожно-строительных машин и тракторов',
            desc: '',
            tmodel: false,
        },
        {
            id: '10',
            idcat2: '3',
            title: 'Для механизаторов',
            desc: '',
            tmodel: false,
        },
        {
            id: '11',
            idcat2: '3',
            title: 'Водительские категории',
            desc: '',
            tmodel: false,
        },
        {
            id: '12',
            idcat2: '3',
            title: 'Категория или подкатегория Тип транспортного средства',
            desc: '',
            tmodel: false,
        },
        {
            id: '13',
            idcat2: '3',
            title: 'В Легковые автомобили, небольшие грузовики (до 3,5 тонн)',
            desc: '',
            tmodel: false,
        },
        {
            id: '14',
            idcat2: '3',
            title: 'ВЕ Легковые автомобили с прицепом',
            desc: '',
            tmodel: false,
        },
        {
            id: '15',
            idcat2: '3',
            title: 'ВІ Трициклы',
            desc: '',
            tmodel: false,
        },
        {
            id: '16',
            idcat2: '3',
            title: 'С Грузовые автомобили (от 3,5 тонн)',
            desc: '',
            tmodel: false,
        },
        {
            id: '17',
            idcat2: '3',
            title: 'СЕ Грузовые автомобили с прицепом',
            desc: '',
            tmodel: false,
        },
        {
            id: '18',
            idcat2: '3',
            title: 'CI Средние грузовики (от 3,5 до 7,5 тонн)',
            desc: '',
            tmodel: false,
        },
        {
            id: '19',
            idcat2: '3',
            title: 'CIE Средние грузовики с прицепом',
            desc: '',
            tmodel: false,
        },
        {
            id: '20',
            idcat2: '3',
            title: 'D Автобусы',
            desc: '',
            tmodel: false,
        },
        {
            id: '21',
            idcat2: '3',
            title: 'DE Автобусы с прицепом',
            desc: '',
            tmodel: false,
        },
        {
            id: '22',
            idcat2: '3',
            title: 'DI Небольшие автобусы',
            desc: '',
            tmodel: false,
        },
        {
            id: '23',
            idcat2: '3',
            title: 'DIE Небольшие автобусы с прицепом',
            desc: '',
            tmodel: false,
        },
        {
            id: '24',
            idcat2: '4',
            title: 'Машинист автомобильного крана',
            desc: '',
            tmodel: false,
        },
        {
            id: '25',
            idcat2: '4',
            title: 'Машинист пневмоколесного крана',
            desc: '',
            tmodel: false,
        },
        {
            id: '26',
            idcat2: '4',
            title: 'Машинист ЦА',
            desc: '',
            tmodel: false,
        },
        {
            id: '27',
            idcat2: '4',
            title: 'Машинист ППУ',
            desc: '',
            tmodel: false,
        },
        {
            id: '28',
            idcat2: '4',
            title: 'Машинист автогрейдера',
            desc: '',
            tmodel: false,
        },
        {
            id: '29',
            idcat2: '4',
            title: 'Машинист буровой установки',
            desc: '',
            tmodel: false,
        },
        {
            id: '30',
            idcat2: '4',
            title: 'Машинист автовышки и автогидроподьемника',
            desc: '',
            tmodel: false,
        },
        {
            id: '31',
            idcat2: '4',
            title: 'Машинист сваебойных установок',
            desc: '',
            tmodel: false,
        },
        {
            id: '32',
            idcat2: '4',
            title: 'Машинист погрузчика',
            desc: '',
            tmodel: false,
        },
        {
            id: '33',
            idcat2: '4',
            title: 'Машинист автокрана гидроманипулятором',
            desc: '',
            tmodel: false,
        },
        {
            id: '34',
            idcat2: '4',
            title: 'Машинист каротажной станции',
            desc: '',
            tmodel: false,
        },
        {
            id: '35',
            idcat2: '4',
            title: 'Машинист лесозаготовительной машины',
            desc: '',
            tmodel: false,
        },
        {
            id: '36',
            idcat2: '4',
            title: 'Машинист трелевочной машиныы',
            desc: '',
            tmodel: false,
        },
        {
            id: '37',
            idcat2: '5',
            title: 'A I',
            desc: '',
            tmodel: false,
        },
        {
            id: '38',
            idcat2: '5',
            title: 'A II',
            desc: '',
            tmodel: false,
        },
        {
            id: '39',
            idcat2: '5',
            title: 'A III',
            desc: '',
            tmodel: false,
        },
        {
            id: '40',
            idcat2: '5',
            title: 'A IV',
            desc: '',
            tmodel: false,
        },
        {
            id: '41',
            idcat2: '5',
            title: 'B',
            desc: '',
            tmodel: false,
        },
        {
            id: '42',
            idcat2: '5',
            title: 'CD',
            desc: '',
            tmodel: false,
        },
        {
            id: '43',
            idcat2: '5',
            title: 'E',
            desc: '',
            tmodel: false,
        },
        {
            id: '44',
            idcat2: '6',
            title: 'Машинист трубоуклада',
            desc: '',
            tmodel: false,
        },
        {
            id: '45',
            idcat2: '6',
            title: 'Машинист экскаватора',
            desc: '',
            tmodel: false,
        },
        {
            id: '46',
            idcat2: '6',
            title: 'Машинист буровой установки',
            desc: '',
            tmodel: false,
        },
        {
            id: '47',
            idcat2: '6',
            title: 'Машинист сваебойных установок',
            desc: '',
            tmodel: false,
        },
        {
            id: '48',
            idcat2: '6',
            title: 'Машинист копра',
            desc: '',
            tmodel: false,
        },
        {
            id: '49',
            idcat2: '7',
            title: 'Бригадир (освобожденный) по текущему содержанию и ремонту пути и искусственных сооружений',
            desc: '',
            tmodel: false,
        },
        {
            id: '50',
            idcat2: '7',
            title: 'Бригадир (освобожденный) предприятий железнодорожного транспорта',
            desc: '',
            tmodel: false,
        },
        {
            id: '51',
            idcat2: '7',
            title: 'Водитель дрезины',
            desc: '',
            tmodel: false,
        },
        {
            id: '52',
            idcat2: '7',
            title: 'Вязальщик польстерных щеток',
            desc: '',
            tmodel: false,
        },
        {
            id: '53',
            idcat2: '7',
            title: 'Дежурный по переезду',
            desc: '',
            tmodel: false,
        },
        {
            id: '54',
            idcat2: '7',
            title: 'Дежурный стрелочного поста',
            desc: '',
            tmodel: false,
        },
        {
            id: '55',
            idcat2: '7',
            title: 'Доставщик перевозочных документов',
            desc: '',
            tmodel: false,
        },
        {
            id: '56',
            idcat2: '7',
            title: 'Кондуктор грузовых поездов',
            desc: '',
            tmodel: false,
        },
        {
            id: '57',
            idcat2: '7',
            title: 'Контролер автоматических пропускных пунктов',
            desc: '',
            tmodel: false,
        },
        {
            id: '58',
            idcat2: '7',
            title: 'Контролер состояния железнодорожного пути',
            desc: '',
            tmodel: false,
        },
        {
            id: '59',
            idcat2: '7',
            title: 'Машинист автомотрисы',
            desc: '',
            tmodel: false,
        },
        {
            id: '60',
            idcat2: '7',
            title: 'Машинист газотрубопровода',
            desc: '',
            tmodel: false,
        },
        {
            id: '61',
            idcat2: '7',
            title: 'Машинист дизельпоезда',
            desc: '',
            tmodel: false,
        },
        {
            id: '62',
            idcat2: '7',
            title: 'Машинист железнодорожно-строительной машины',
            desc: '',
            tmodel: false,
        },
        {
            id: '63',
            idcat2: '7',
            title: 'Машинист моечной установки',
            desc: '',
            tmodel: false,
        },
        {
            id: '64',
            idcat2: '7',
            title: 'Машинист мотоваза',
            desc: '',
            tmodel: false,
        },
        {
            id: '65',
            idcat2: '7',
            title: 'Машинист насосной установки железнодорожного водоснабжения',
            desc: '',
            tmodel: false,
        },
        {
            id: '66',
            idcat2: '7',
            title: 'Машинист паровоза',
            desc: '',
            tmodel: false,
        },
        {
            id: '67',
            idcat2: '7',
            title: 'Машинист самоходного весоповерочного вагона',
            desc: '',
            tmodel: false,
        },
        {
            id: '68',
            idcat2: '7',
            title: 'Машинист тепловоза',
            desc: '',
            tmodel: false,
        },
        {
            id: '69',
            idcat2: '7',
            title: 'Машинист уборочных машин',
            desc: '',
            tmodel: false,
        },
        {
            id: '70',
            idcat2: '7',
            title: 'Машинист установок по обслуживанию подвижного состава',
            desc: '',
            tmodel: false,
        },
        {
            id: '71',
            idcat2: '7',
            title: 'Машинист электровоза',
            desc: '',
            tmodel: false,
        },
        {
            id: '72',
            idcat2: '7',
            title: 'Машинист электропоезда',
            desc: '',
            tmodel: false,
        },
        {
            id: '73',
            idcat2: '7',
            title: 'Мойщик-уборщик подвижного состава',
            desc: '',
            tmodel: false,
        },
        {
            id: '74',
            idcat2: '7',
            title: 'Монтер пути',
            desc: '',
            tmodel: false,
        },
        {
            id: '75',
            idcat2: '7',
            title: 'Моторист поворотного состава',
            desc: '',
            tmodel: false,
        },
        {
            id: '76',
            idcat2: '7',
            title: 'Наладчик железнодорожно-строительных машин и механизмов',
            desc: '',
            tmodel: false,
        },
        {
            id: '77',
            idcat2: '7',
            title: 'Наладчик контрольно-измерительных машин и механизмов',
            desc: '',
            tmodel: false,
        },
        {
            id: '78',
            idcat2: '7',
            title: 'Наладчик контрольно-измерительных вагонов',
            desc: '',
            tmodel: false,
        },
        {
            id: '79',
            idcat2: '7',
            title: 'Обходчик пути и искусственных сооружений',
            desc: '',
            tmodel: false,
        },
        {
            id: '80',
            idcat2: '7',
            title: 'Оператор дефектоскопной тележки',
            desc: '',
            tmodel: false,
        },
        {
            id: '81',
            idcat2: '7',
            title: 'Оператор по обслуживанию и ремонту вагонов и контейнеров',
            desc: '',
            tmodel: false,
        },
        {
            id: '82',
            idcat2: '7',
            title: 'Оператор по путевым измерениям',
            desc: '',
            tmodel: false,
        },
        {
            id: '83',
            idcat2: '7',
            title: 'Оператор поста централизации',
            desc: '',
            tmodel: false,
        },
        {
            id: '84',
            idcat2: '7',
            title: 'Оператор сортировочной горки',
            desc: '',
            tmodel: false,
        },
        {
            id: '85',
            idcat2: '7',
            title: 'Осмотрщик-ремонтник вагонов',
            desc: '',
            tmodel: false,
        },
        {
            id: '86',
            idcat2: '7',
            title: 'Поездной электромеханик',
            desc: '',
            tmodel: false,
        },
        {
            id: '87',
            idcat2: '7',
            title: 'Помощник машиниста газотрубовоза',
            desc: '',
            tmodel: false,
        },
        {
            id: '88',
            idcat2: '7',
            title: 'Помощник машиниста паровоза',
            desc: '',
            tmodel: false,
        },
        {
            id: '89',
            idcat2: '7',
            title: 'Помощник машиниста рельсового автобуса',
            desc: '',
            tmodel: false,
        },
        {
            id: '90',
            idcat2: '7',
            title: 'Помощник машиниста тепловоза',
            desc: '',
            tmodel: false,
        },
        {
            id: '91',
            idcat2: '7',
            title: 'Помощник машиниста электровоза',
            desc: '',
            tmodel: false,
        },
        {
            id: '92',
            idcat2: '7',
            title: 'Помощник машиниста электровопоезда',
            desc: '',
            tmodel: false,
        },
        {
            id: '93',
            idcat2: '7',
            title: 'Прессовщик колесных пар',
            desc: '',
            tmodel: false,
        },
        {
            id: '94',
            idcat2: '7',
            title: 'Приемосдатчик груза и багажа в поездах',
            desc: '',
            tmodel: false,
        },
        {
            id: '95',
            idcat2: '7',
            title: 'Приемщик поездов',
            desc: '',
            tmodel: false,
        },
        {
            id: '96',
            idcat2: '7',
            title: 'Проводник пассажирского вагона',
            desc: '',
            tmodel: false,
        },
        {
            id: '97',
            idcat2: '7',
            title: 'Проводник по сопровождению грузов и спецвагонов',
            desc: '',
            tmodel: false,
        },
        {
            id: '98',
            idcat2: '7',
            title: 'Проводник по сопровождению локомотивов и пассажирских вагонов в нерабочем состоянии',
            desc: '',
            tmodel: false,
        },
        {
            id: '99',
            idcat2: '7',
            title: 'Промывальщик котлов паровозов',
            desc: '',
            tmodel: false,
        },
        {
            id: '100',
            idcat2: '7',
            title: 'Промывальщик-пропарщик цистерн',
            desc: '',
            tmodel: false,
        },
        {
            id: '101',
            idcat2: '7',
            title: 'Рабочий по обслуживанию локомотива на железнодорожных путях без передвижения',
            desc: '(группы локомотивов)',
            tmodel: false,
        },
        {
            id: '102',
            idcat2: '7',
            title: 'Регулировщик скорости движения вагонов',
            desc: '',
            tmodel: false,
        },
        {
            id: '103',
            idcat2: '7',
            title: 'РЕмонтник искусственных сооружений',
            desc: '',
            tmodel: false,
        },
        {
            id: '104',
            idcat2: '7',
            title: 'Сигналист',
            desc: '',
            tmodel: false,
        },
        {
            id: '105',
            idcat2: '7',
            title: 'Слесарь по осмотру и ремонту локомотивов на пунктах технического обслуживания',
            desc: '',
            tmodel: false,
        },
        {
            id: '106',
            idcat2: '7',
            title: 'Составитель поездов',
            desc: '',
            tmodel: false,
        },
        {
            id: '107',
            idcat2: '7',
            title: 'Станционный рабочий',
            desc: '',
            tmodel: false,
        },
        {
            id: '108',
            idcat2: '7',
            title: 'Тоннельный рабочий',
            desc: '',
            tmodel: false,
        },
        {
            id: '109',
            idcat2: '7',
            title: 'Экипировщик',
            desc: '',
            tmodel: false,
        },
        {
            id: '110',
            idcat2: '7',
            title: 'Электромонтер контактной сети',
            desc: '',
            tmodel: false,
        },
        {
            id: '111',
            idcat2: '7',
            title: 'Электромонтер по ремонту и обслуживанию аппаратуры и устройств связи',
            desc: '',
            tmodel: false,
        },
        {
            id: '112',
            idcat2: '7',
            title: 'Электромонтер по обслуживанию и ремонту устройств сигнализации, централизации и блокировки',
            desc: '',
            tmodel: false,
        },
        {
            id: '113',
            idcat2: '7',
            title: 'Электромонтер тяговой подстанции',
            desc: '',
            tmodel: false,
        },
        {
            id: '114',
            idcat2: '7',
            title: 'Газовое хозяйство городов, поселков и населенных пунктов',
            desc: '',
            tmodel: false,
        },
        {
            id: '115',
            idcat2: '7',
            title: 'Аппаратчик испарительной установки',
            desc: '',
            tmodel: false,
        },
        {
            id: '116',
            idcat2: '7',
            title: 'Контролер печного хозяйства',
            desc: '',
            tmodel: false,
        },
        {
            id: '117',
            idcat2: '7',
            title: 'Машинист газораздаточной станции',
            desc: '',
            tmodel: false,
        },
        {
            id: '118',
            idcat2: '7',
            title: 'Оператор газольдерной станции',
            desc: '',
            tmodel: false,
        },
        {
            id: '119',
            idcat2: '7',
            title: 'Слесарь аварийно-восстановительных работ в газовом хозяйстве',
            desc: '',
            tmodel: false,
        },
        {
            id: '120',
            idcat2: '7',
            title: 'Слесарь по эксплуатации и ремонту подземных газопроводов',
            desc: '',
            tmodel: false,
        },
        {
            id: '121',
            idcat2: '7',
            title: 'Слесарь по эксплуатации и ремонту газового оборудования',
            desc: '',
            tmodel: false,
        },
        {
            id: '122',
            idcat2: '7',
            title: 'Электрогазосварщик-врезчик',
            desc: '',
            tmodel: false,
        },
        {
            id: '123',
            idcat2: '8',
            title: 'Машинист ДЭС',
            desc: '',
            tmodel: false,
        },
        {
            id: '124',
            idcat2: '8',
            title: 'Машинист ЦА',
            desc: '',
            tmodel: false,
        },
        {
            id: '125',
            idcat2: '8',
            title: 'Машинист насосной станции',
            desc: '',
            tmodel: false,
        },
        {
            id: '126',
            idcat2: '9',
            title: 'Машинист ДЭС',
            desc: '',
            tmodel: false,
        },


        {
            id: '127',
            idcat1: '4',
            title: 'Главный энергетик',
            desc: '',
            tmodel: false,
        },
        {
            id: '128',
            idcat1: '4',
            title: 'Диспетчер',
            desc: '',
            tmodel: false,
        },
        {
            id: '129',
            idcat1: '4',
            title: 'Кладовщик',
            desc: '',
            tmodel: false,
        },
        {
            id: '130',
            idcat1: '5',
            title: 'Начальник вахтового лагеря',
            desc: '',
            tmodel: false,
        },
        {
            id: '131',
            idcat1: '5',
            title: 'Начальник склада',
            desc: '(кладовщик)',
            tmodel: false,
        },
        {
            id: '132',
            idcat1: '5',
            title: 'Комендант общежития',
            desc: '',
            tmodel: false,
        },
        {
            id: '133',
            idcat1: '5',
            title: 'Повар',
            desc: '',
            tmodel: false,
        },
        {
            id: '134',
            idcat1: '5',
            title: 'Вахтер',
            desc: '',
            tmodel: false,
        },
        {
            id: '135',
            idcat1: '5',
            title: 'Горничная',
            desc: '',
            tmodel: false,
        },
        {
            id: '136',
            idcat1: '5',
            title: 'Кухонный рабочий',
            desc: '',
            tmodel: false,
        },
        {
            id: '137',
            idcat1: '5',
            title: 'Плотник',
            desc: '',
            tmodel: false,
        },
        {
            id: '138',
            idcat1: '7',
            title: 'Врач общей практики',
            desc: '',
            tmodel: false,
        },
        {
            id: '139',
            idcat2: '17',
            title: 'Старшая медсестра',
            desc: '',
            tmodel: false,
        },
        {
            id: '140',
            idcat1: '7',
            title: 'Фельдшер',
            desc: '',
            tmodel: false,
        },
        {
            id: '141',
            idcat1: '7',
            title: 'Медсестра',
            desc: '',
            tmodel: false,
        },
        {
            id: '142',
            idcat1: '7',
            title: 'Медбрат',
            desc: '',
            tmodel: false,
        },
        {
            id: '143',
            idcat1: '6',
            title: '',
            desc: '',
            tmodel: false,
        },

    ];





}